name: app_environment
channels:
  - snowflake
dependencies:
  - python=3.8.*
  - snowflake-snowpark-python=1.20.0
  - streamlit=1.35.0
  - snowflake-ml-python=1.6.2
  - snowflake.core=0.12.1
  - tabulate=0.9.0