name: snowcomment_env
channels:
  - snowflake
  - conda-forge
dependencies:
  - python=3.8.*
  - snowflake-snowpark-python=1.20.0
  - streamlit=1.35.0
  - snowflake-ml-python=1.6.2
  - tabulate=0.9.0
  - pip
  - pip:
    - snowflake
    - python-dotenv